money/config/routes.rb
Money::Application.routes.draw do
  get "payments/index"

  root 'payments#index'

  resources :payments

end

money/app/models/payment.rb
class Payment < ActiveRecord::Base
end

money/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

money/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
 	def new
  		@payment = Payment.new
  	end
  	 
  	def index
  		@payments = Payment.all
  	end

  	def show
  		@payment = Payment.find(params[:id])
	end

	def destroy
  		@payment = Payment.find(params[:id])
  		@payment.destroy
 
  		redirect_to payments_path
	end
  	
  	def edit
  		@payment = Payment.find(params[:id])
	end

	def update
  		@payment = Payment.find(params[:id])
 
  		if @payment.update(params[:payment].permit(:hiduke, :kingaku, :bikou))
    		redirect_to @payment
  		else
    		render 'edit'
  		end
	end

  	def create
		@payment = Payment.new(payment_params)

  		if @payment.save
    		redirect_to @payment
  		else
    		render 'new'
 		end
	end

	private
  	 def payment_params
    	params.require(:payment).permit(:hiduke, :kingaku, :bikou)
  	 end
	
end

money/app/helpers/application_helper.rb
module ApplicationHelper
end

money/app/helpers/payments_helper.rb
module PaymentsHelper
end

money/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Money</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

money/app/views/payments/_form.html.erb
<%= form_for @payment do |f| %>
  <p>
    <%='消費日付'%><br>
    <%= f.text_field :hiduke %>
  </p>
 
  <p>
    <%= '金額' %><br>
    <%= f.text_field :kingaku %>
  </p>

   <p>
    <%= '備考' %><br>
    <%= f.text_area :bikou %>
  </p>

  <p>
    <%=f.submit%>
  </p>
<% end %>
 

money/app/views/payments/edit.html.erb
<h3>変更</h3>
 
<%= render 'form' %>

<%= link_to '戻る', payments_path %>

money/app/views/payments/index.html.erb
<h1>消費一覧</h1>



<%= link_to '追加', new_payment_path %>

<table>
  <tr>
    <th>消費日付</th>
    <th>金額</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.hiduke %></td>
    <td><%= payment.kingaku %></td>
    <td><%= link_to '詳細', payment_path(payment) %></td>
    <td><%= link_to '変更', edit_payment_path(payment) %></td>
    <td><%= link_to '削除', payment_path(payment),
                    method: :delete, data: { confirm: '削除してもよろしいですか?' } %></td>
  </tr>
<% end %>
</table>

money/app/views/payments/new.html.erb
<h3>新規</h3>

<%= render 'form' %>

<%= link_to '戻る', payments_path %>

money/app/views/payments/show.html.erb
<h3>詳細</h3>

<p>
  <strong>消費日付:</strong>
  <%= @payment.hiduke %>
</p>
<p>
  <strong>金額:</strong>
  <%= @payment.kingaku %>
</p>
 <p>
  <strong>備考:</strong>
  <%= @payment.bikou %>
</p>
 
 <%= link_to '戻る', payments_path %>